CGA.NET-master/CGA-WEB/Controllers/ClaimController.cs
using CGA_WEB.Models;
using Domain.Entities;
using Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CGA_WEB.Controllers
{
    public class ClaimController : Controller
    {


        ClaimService claimService = new ClaimService();

        // GET: Claim
        public ActionResult Index(String searchString)
        {
            List<ClaimModel> List = new List<ClaimModel>();
            foreach (var item in claimService.GetAll())
            {
                ClaimModel cm = new ClaimModel();

                cm.id = item.id;
                cm.etat = item.etat;
                cm.cinInsured2 = item.cinInsured2;
                cm.contract_id = item.contract_id;
                cm.accidentDate = item.accidentDate;
                cm.localisation = item.localisation;

                List.Add(cm);
            }
            var finds = from m in List
                        select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                finds = finds.Where(s => s.localisation.Contains(searchString)).AsEnumerable();
            }

            return View(finds);
        }

        // GET: Claim/Details/5
        public ActionResult Details(int id)
        {
            ClaimModel cm = new ClaimModel();
            claim c = claimService.GetById(id);
            cm.ImageUrl = c.ImageUrl;
            cm.localisation = c.localisation;
            cm.accidentDate = c.accidentDate;
            cm.cinInsured2 = c.cinInsured2;
            cm.injured = c.injured;
            cm.namesAddressesPhonesWitnesses = c.namesAddressesPhonesWitnesses;
            cm.vehiclesDamage = c.vehiclesDamage;
            c.etat = c.etat;
            cm.contract_id = c.contract_id;

            return View(cm);
        }

        // GET: Claim/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Claim/Create
        [HttpPost]
        public ActionResult Create(claim cm, HttpPostedFileBase Image, int id)
        {
            if (string.IsNullOrWhiteSpace(cm.cinInsured2) )
            {

                return View(cm);
            }
            {
               cm.ImageUrl = Image.FileName;
            claim c = new claim
            {
                cinInsured2 = cm.cinInsured2,
                contract_id = id,
                accidentDate = cm.accidentDate,
                localisation = cm.localisation,
                lang = cm.lang,
                lat = cm.lat,
                namesAddressesPhonesWitnesses = cm.namesAddressesPhonesWitnesses,
                ImageUrl = cm.ImageUrl,
                otherObjectDamage = cm.otherObjectDamage,
                injured = cm.injured,
                vehiclesDamage = cm.vehiclesDamage,
                etat = "waiting"



            };

        var path = Path.Combine(Server.MapPath("~/Content/Upload/"), Image.FileName);
        Image.SaveAs(path);
                claimService.Add(c);
            claimService.Commit();  

            return RedirectToAction("Index");
    }
            
        }
        

        // GET: Claim/Edit/5
        public ActionResult Edit(int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit");
            }
            else
            {
                ClaimModel cm = new ClaimModel();
                claim c = claimService.GetById(id);
                cm.id = c.id;
                cm.ImageUrl = c.ImageUrl;
                cm.localisation = c.localisation;
                cm.accidentDate = c.accidentDate;
                cm.cinInsured2 = c.cinInsured2;
                cm.injured = c.injured;
                cm.namesAddressesPhonesWitnesses = c.otherObjectDamage;
                cm.vehiclesDamage = c.vehiclesDamage;
                c.etat = c.etat;
                cm.contract_id = c.contract_id;

                return View(cm);
            } }

        // POST: Claim/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ClaimModel cm)
        {
            claim c = claimService.GetById(id);
            c.ImageUrl = cm.ImageUrl;
            c.localisation = cm.localisation;
            c.accidentDate = cm.accidentDate;
            c.cinInsured2 = cm.cinInsured2;
            c.injured = cm.injured;
            c.namesAddressesPhonesWitnesses = cm.otherObjectDamage;
            c.vehiclesDamage = cm.vehiclesDamage;
            c.etat = cm.etat;
            c.contract_id = cm.contract_id;
            claimService.Update(c);
            claimService.Commit();

            return RedirectToAction("Index");

        }
        

        // GET: Claim/Delete/5
        public ActionResult Delete(int id)
        {
            claimService.Delete(claimService.GetById(id));
            claimService.Commit();


            return RedirectToAction("Index");
        }

        // POST: Claim/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ClaimModel cm)
        {
            claim c = claimService.GetById(id);
            c.ImageUrl = cm.ImageUrl;
            c.localisation = cm.localisation;
            c.accidentDate = cm.accidentDate;
            c.cinInsured2 = cm.cinInsured2;
            c.injured = cm.injured;
            c.namesAddressesPhonesWitnesses = cm.otherObjectDamage;
            c.vehiclesDamage = cm.vehiclesDamage;
            c.etat = cm.etat;
            c.contract_id = cm.contract_id;
            claimService.Delete(c);
            claimService.Commit();

            return RedirectToAction("Index");
            }
        }
   
}

CGA.NET-master/CGA-WEB/Views/Claim/Create.cshtml
@model Domain.Entities.claim

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h2>Create</h2>
<script src=@Url.Content("~/Scripts/jquery-1.10.2.js")></script>
<script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: { lat: 36.862499, lng: 10.195556 },
            zoom: 9,
            mapTypeId: google.maps.MapTypeId.TERRAIN
        });


    }

    $(document).ready(function () {
        $("#k").click(function () {
            var map;

                map = new google.maps.Map(document.getElementById('map'), {
                    center: { lat: 36.862499, lng: 10.195556 },
                    zoom: 8,
                    mapTypeId: google.maps.MapTypeId.TERRAIN
                });



            var geocoder;
        geocoder = new google.maps.Geocoder();
        var address = document.getElementById('localisation').value;

            geocoder.geocode( { 'address': address}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location,

                    });
                }

                    document.getElementById('lat').value = marker.getPosition().lat();
                    document.getElementById('lang').value = marker.getPosition().lng();

            });
        })

    })
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0lGurDaolJ4wzpaDkKNjWst84beoHRyw&callback=initMap"
        type="text/javascript">
</script>
@using (Html.BeginForm("Create", "Claim", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>claim</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.accidentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.accidentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.accidentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localisation, "", new { @class = "text-danger" })
            </div>
            <div style="margin-left:400px ">
                <input type="button" value="Locate" id="k" class="button" style="width:100px"/ >
            </div>
            <div id="map" style="height: 400px; width: 600px ; margin-left: 250px">

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.namesAddressesPhonesWitnesses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.namesAddressesPhonesWitnesses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.namesAddressesPhonesWitnesses, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Image", null, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.cinInsured2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" id="cinInsured2">
                @Html.EditorFor(model => model.cinInsured2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cinInsured2, "", new { @class = "text-danger" })
               
                <asp:RangeValidator ControlToValidate="tb" Type="Integer"></asp:RangeValidator>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lat, "", new { @class = "text-danger" })
            </div>
        </div>



       >

        <div class="form-group">
            @Html.LabelFor(model => model.injured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.injured, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.injured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.otherObjectDamage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.otherObjectDamage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.otherObjectDamage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vehiclesDamage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vehiclesDamage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vehiclesDamage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send Claim" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CGA.NET-master/CGA-WEB/Views/Claim/Details.cshtml
@model CGA_WEB.Models.ClaimModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>See More...</h2>


    
    <hr />
    <div style="margin-top:100px ; float:left ; margin-bottom:100px ; margin-left:50px"   >
        @*recuperer l'image*@
        @{string path = "~/Content/Upload/" + Model.ImageUrl;}
        @*enlever label for pour afficher seulement l'image*@
        <img src="@Url.Content(path)" width="200" height="200" onchange="onFileSelected(event)" alt="Norway" width="1000" height="350" style="border-radius: 8px;" />
    </div>
<div>
    <center>
        <dl class="dl-horizontal" style="margin-top:50px">


            <dt>
                Accident Date : @Html.DisplayFor(model => model.accidentDate)
            </dt>
            <br />
            <dt>
                Localisation : @Html.DisplayFor(model => model.localisation)
            </dt>
            <br />
            <dt>
                About Witnesses : @Html.DisplayFor(model => model.namesAddressesPhonesWitnesses)
            </dt>
            <br />

            <dt>
                Cin of Insured 2 : @Html.DisplayFor(model => model.cinInsured2)
            </dt>
            <br />

            <dt>
                Status of your claim : @Html.DisplayFor(model => model.etat)
            </dt>
            <br />

            <dt>
                Contract Num : @Html.DisplayFor(model => model.contract_id)
            </dt>
            <br />

            <dt>
                Injured number : @Html.DisplayFor(model => model.injured)
            </dt>
            <br />
            <dt>
                Description : @Html.DisplayFor(model => model.otherObjectDamage)

            </dt>
            <br />

            <dt>
                Vehicles damage number : @Html.DisplayFor(model => model.vehiclesDamage)
            </dt>

        </dl>
    </center>

</div>

<p>
    @Html.ActionLink("My Claims", "Index")
</p>

CGA.NET-master/CGA-WEB/Views/Claim/Edit.cshtml
@model CGA_WEB.Models.ClaimModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<script src=@Url.Content("~/Scripts/jquery-1.10.2.js")></script>
<script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: { lat: 36.862499, lng: 10.195556 },
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.TERRAIN
        });


    }

    $(document).ready(function () {
        $("#k").click(function () {
            var map;

                map = new google.maps.Map(document.getElementById('map'), {
                    center: { lat: 36.862499, lng: 10.195556 },
                    zoom: 8,
                    mapTypeId: google.maps.MapTypeId.TERRAIN
                });



            var geocoder;
        geocoder = new google.maps.Geocoder();
        var address = document.getElementById('localisation').value;

            geocoder.geocode( { 'address': address}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location,

                    });
                }
             //   alert(marker.getPosition().lat());

                    document.getElementById('lat').value = marker.getPosition().lat();
                    document.getElementById('lang').value = marker.getPosition().lng();
               //     alert(marker.getPosition().lat());

            });
        })

    })
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0lGurDaolJ4wzpaDkKNjWst84beoHRyw&callback=initMap"
        type="text/javascript">
</script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClaimModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.accidentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.accidentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.accidentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localisation, "", new { @class = "text-danger" })
            </div>
            <div style="margin-left:400px ">
                <input type="button" value="Locate" id="k" class="button" style="width:100px"/ >
            </div>
            <div id="map" style="height: 600px; width: 900px ; margin-left: 250px">

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.namesAddressesPhonesWitnesses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.namesAddressesPhonesWitnesses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.namesAddressesPhonesWitnesses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cinInsured2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cinInsured2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cinInsured2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.etat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.etat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.etat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contract_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contract_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contract_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.injured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.injured, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.injured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.otherObjectDamage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.otherObjectDamage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.otherObjectDamage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vehiclesDamage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.vehiclesDamage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.vehiclesDamage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "Claim")" class="btn btn-primary">
        My Claims
        <span class="glyphicon btn-primary" aria-hidden="true"></span>
    </a>
    @Html.ActionLink("My Claims", "Index")
</div>

CGA.NET-master/CGA-WEB/Views/Claim/Index.cshtml
@model IEnumerable<CGA_WEB.Models.ClaimModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<form asp-controller="Claim" asp-action="Index">
    <p style="margin:40px">
        Loclisation: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.accidentDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.localisation)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.cinInsured2)
        </th>
     
        <th>
            @Html.DisplayNameFor(model => model.etat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contract_id)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.accidentDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.localisation)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.cinInsured2)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.etat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contract_id)
        </td>
      
        <td>
            <a href="@Url.Action("Delete", "Claim", new { id = item.id })" class="btn btn-danger">
                Delete
                <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
            </a>
            <a href="@Url.Action("Edit", "Claim", new { id = item.id })" class="btn btn-success">
                Edit
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </a>
            <a href="@Url.Action("Details", "Claim", new { id = item.id })" class="btn btn-info">
                Details
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
            </a>

        </td>
    </tr>
}

</table>