CGA.NET-master/CGA-WEB/Controllers/CommentaireController.cs
using CGA_WEB.Models;
using Domain.Entities;
using RestSharp;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CGA_WEB.Controllers
{
    public class CommentaireController : Controller
    {
        UserService us = null;
        CommentaireService cmS = null;
        public CommentaireController()
        {
            cmS = new CommentaireService();
            us = new UserService();
        }


        // GET: Commentaire
        public ActionResult Index1(CommentaireModels cm )
        {
           
            ViewData["nbre"]= cmS.nbreCommentaireByPolicy((int)Session["id"]);
            ViewData["nbreC"] = cmS.nbreCommentaireNonVu();
            cm.users = cmS.UserWithCommentaireNonVu();
          cm.commentaires   = cmS.sortById((int)Session["id"]);

            return View(cm);
        }

        // GET: Commentaire/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Commentaire/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Commentaire/Create
        [HttpPost]
        public ActionResult Create(String txt)
        {
            Session["msg"] ="false";
            List<String> verif = new List<String>();
            

            commentaire com = new commentaire()
            
            {
             
                user_id=2,
                status = 0,
                like = 0,
                policy_id = (int)Session["id"],
                text = txt,
                
                date= DateTime.Now.ToString("MM/dd/yyyy"),

            };

            {
                
                Char delimiter = ' ';
                String[] substrings = txt.Split(delimiter);
                foreach (var substring in substrings)
                    verif.Add(substring);
            }
            if (verif.Contains("sexe")|| verif.Contains("bad") || verif.Contains("chet") || verif.Contains("chet up "))
            {
                Session["msg"] ="true";
                return RedirectToAction("Index1");
            }
            else
            {
                Session["msg"] = "false";
                cmS.Add(com);
                cmS.Commit();
                ViewBag.err = "this commentaire contais bad word";

                return RedirectToAction("Index1");
            }
        }

        // GET: Commentaire/Edit/5
        public ActionResult Edit(int id)
        {
            commentaire com = cmS.GetById(id);
            
            CommentaireModels CM = new CommentaireModels()
            {
                text = com.text,
                id=com.id,


            };

            return View(CM);
        }

        // POST: Commentaire/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CommentaireModels CM)
        {
            Session["msg"] = "false";
            commentaire com = cmS.GetById(id);


            com.text = CM.text;
           
               cmS.Update(com);
                UpdateModel(CM);

               cmS.Commit();
                return RedirectToAction("Index1");


           
           

            
        }

        // GET: Commentaire/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    commentaire com = cmS.GetById(id);
        //    if (com == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    CommentaireModels CM= new CommentaireModels()
        //    {
        //        text =com.text,
               


        //    };

        //    return View(CM);
        //}

        // POST: Commentaire/Delete/5
       
        public ActionResult Delete(int id)
        {
            Session["msg"] = "false";
            commentaire com = cmS.GetById(id);
            cmS.Delete(com);
            cmS.Commit();
          
            return RedirectToAction("Index1");
        }

        public ActionResult nbreCommentaire()
        {
            int x = cmS.nbreCommentaireByPolicy(1);

            return View(x);
        }
        public ActionResult Like(int id)
        {
            commentaire com = cmS.GetById(id);


            com.like += 1;

            cmS.Update(com);
            

            cmS.Commit();


            return RedirectToAction("Index1");
        }
        public ActionResult DisLike(int id)
        {
            commentaire com = cmS.GetById(id);
            Session["msg"] = "false";

            com.like -= 1;

            cmS.Update(com);


            cmS.Commit();


            return RedirectToAction("Index1");
        }

        public ActionResult Policy()
        {
            Session["msg"] = "false";
            var contrats = new RestClient("http://localhost:8080/cga-web/pidev/CgaPolicy/");
            var request = new RestRequest("getPolicy", Method.GET);
            request.AddHeader("Content-type", "application/json");
            IRestResponse<List<policy>> contrat = contrats.Execute<List<policy>>(request);
            return View(contrat.Data);
        }
        public ActionResult Index2(CommentaireModels cm, int id=2 )
        {
            Session["id"] = id;
            ViewData["nbre"] = cmS.nbreCommentaireByPolicy((int)Session["id"]);
            ViewData["nbreC"] = cmS.nbreCommentaireNonVu();
            cm.users = cmS.UserWithCommentaireNonVu();
            cm.commentaires = cmS.sortById((int)Session["id"]);

            return View(cm);
        }
    }
}

CGA.NET-master/CGA-WEB/Views/Commentaire/Index.cshtml
@model IEnumerable<Domain.Entities.commentaire>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
<style>

.panel-shadow {
    box-shadow: rgba(0, 0, 0, 0.3) 7px 7px 7px;
}
.panel-white {
  border: 1px solid #dddddd;
}
.panel-white  .panel-heading {
  color: #333;
  background-color: #fff;
  border-color: #ddd;
}
.panel-white  .panel-footer {
  background-color: #fff;
  border-color: #ddd;
}

.post .post-heading {
  height: 95px;
  padding: 20px 15px;
}
.post .post-heading .avatar {
  width: 60px;
  height: 60px;
  display: block;
  margin-right: 15px;
}
.post .post-heading .meta .title {
  margin-bottom: 0;
}
.post .post-heading .meta .title a {
  color: black;
}
.post .post-heading .meta .title a:hover {
  color: #aaaaaa;
}
.post .post-heading .meta .time {
  margin-top: 8px;
  color: #999;
}
.post .post-image .image {
  width: 100%;
  height: auto;
}
.post .post-description {
  padding: 15px;
}
.post .post-description p {
  font-size: 14px;
}
.post .post-description .stats {
  margin-top: 20px;
}
.post .post-description .stats .stat-item {
  display: inline-block;
  margin-right: 15px;
}
.post .post-description .stats .stat-item .icon {
  margin-right: 8px;
}
.post .post-footer {
  border-top: 1px solid #ddd;
  padding: 15px;
}
.post .post-footer .input-group-addon a {
  color: #454545;
}
.post .post-footer .comments-list {
  padding: 0;
  margin-top: 20px;
  list-style-type: none;
}
.post .post-footer .comments-list .comment {
  display: block;
  width: 100%;
  margin: 20px 0;
}
.post .post-footer .comments-list .comment .avatar {
  width: 35px;
  height: 35px;
}
.post .post-footer .comments-list .comment .comment-heading {
  display: block;
  width: 100%;
}
.post .post-footer .comments-list .comment .comment-heading .user {
  font-size: 14px;
  font-weight: bold;
  display: inline;
  margin-top: 0;
  margin-right: 10px;
}
.post .post-footer .comments-list .comment .comment-heading .time {
  font-size: 12px;
  color: #aaa;
  margin-top: 0;
  display: inline;
}
.post .post-footer .comments-list .comment .comment-body {
  margin-left: 50px;
}
.post .post-footer .comments-list .comment > .comments-list {
  margin-left: 50px;
}
.notf{
background-color: #dfedff;
color:white;
position:absolute;
width:300px;
top:50px;
height:40px;
right:0px;
text-align:center;
border-bottom:3px;
border-color:black;
}

</style>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
<script>
    $(function () {
        $("#close").click(function () {
            $("#notification").slideUp('slow');

        })
        $("#not").click(function () {
            $("#notification").slideDown('slow');

        })



    });
       


  
    </script>

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">WebSiteName</a>
            </div>
           
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"id="not" ><span class="label label-pill label-danger count"></span> Notification</a>
                   
                </li>
               
            </ul>
        </div>
    </nav>
   
    @foreach (var item in @Html.Encode(ViewData["com"]))
    {
     <div id="notification" class="notf">
        
       
        <button type="button" class="close" aria-label="Close" id="close">
            <span aria-hidden="true">&times;</span>
        </button>

    </div> 

    }

     <div class="title h5" style="margin-left:20px">
       <b> nbre de commentaires @Html.Encode(ViewData["nbre"])</b>

    </div>
    <br/>
    <div class="title h5" style="margin-left:20px">
        @ViewBag.err</div>

        <div class="container" style="width:80%;margin-left:20px;">
            <div class="row" style="height:0px;">
                @foreach (var item in Model)
                {
                    <div class="col-sm-8">
                        <div class="panel panel-white post panel-shadow">
                            <div class="post-heading">
                                <div class="pull-left image">
                                    <img src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar" alt="user profile image">
                                </div>
                                <div class="pull-left meta">
                                    <div class="title h5">
                                        <a href="#"><b>Ryan Haywood</b></a>

                                    </div>
                                    <h6 class="text-muted time">@Html.DisplayFor(modelItem => item.date)</h6>
                                </div>
                            </div>
                            <div class="post-description">
                                <p>@Html.DisplayFor(modelItem => item.text)</p>
                                <div class="stats">
                                   
                                    <a href="@Url.Action("Like", "Commentaire", new { id = item.id })" class="btn btn-default stat-item">
                                        <i class="fa fa-thumbs-up icon"></i>@Html.DisplayFor(modelItem => item.like) 
                                    </a>
                                    <br/>
                                    @if (item.user_id == 1)
                                    {

                                        <a href="@Url.Action("Edit", "Commentaire", new { id = item.id })" style="color:forestgreen" class="btn btn-default btn-sm">
                                            <i class="glyphicon glyphicon-edit"></i>
                                            <span>
                                                <strong>Edit</strong>
                                            </span>
                                        </a>



                                        <a href="@Url.Action("delete", "Commentaire", new { id = item.id })" style="color:forestgreen" class="btn btn-default btn-sm">
                                            <i class="glyphicon btn-default"></i>
                                            <span>
                                                <strong>delete</strong>
                                            </span>
                                        </a>




                                    }
                                    <br />

                                </div>
                            </div>
                        </div>
                    </div>
                }

                @using (Html.BeginForm("Create", "Commentaire"))
                {
                    <input type="text" id="txt" name="txt" class="form-control" rows="3" />
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" id="comment" class="btn-info" />
                    </div>
                }

            </div>
        </div>





</body>
</html>

CGA.NET-master/CGA-WEB/Views/Commentaire/Index1.cshtml
@model CGA_WEB.Models.CommentaireModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
<style>

.panel-shadow {
    box-shadow: rgba(0, 0, 0, 0.3) 7px 7px 7px;
}
.panel-white {
  border: 1px solid #dddddd;
}
.panel-white  .panel-heading {
  color: #333;
  background-color: #fff;
  border-color: #ddd;
}
.panel-white  .panel-footer {
  background-color: #fff;
  border-color: #ddd;
}

.post .post-heading {
  height: 95px;
  padding: 20px 15px;
}
.post .post-heading .avatar {
  width: 60px;
  height: 60px;
  display: block;
  margin-right: 15px;
}
.post .post-heading .meta .title {
  margin-bottom: 0;
}
.post .post-heading .meta .title a {
  color: black;
}
.post .post-heading .meta .title a:hover {
  color: #aaaaaa;
}
.post .post-heading .meta .time {
  margin-top: 8px;
  color: #999;
}
.post .post-image .image {
  width: 100%;
  height: auto;
}
.post .post-description {
  padding: 15px;
}
.post .post-description p {
  font-size: 14px;
}
.post .post-description .stats {
  margin-top: 20px;
}
.post .post-description .stats .stat-item {
  display: inline-block;
  margin-right: 15px;
}
.post .post-description .stats .stat-item .icon {
  margin-right: 8px;
}
.post .post-footer {
  border-top: 1px solid #ddd;
  padding: 15px;
}
.post .post-footer .input-group-addon a {
  color: #454545;
}
.post .post-footer .comments-list {
  padding: 0;
  margin-top: 20px;
  list-style-type: none;
}
.post .post-footer .comments-list .comment {
  display: block;
  width: 100%;
  margin: 20px 0;
}
.post .post-footer .comments-list .comment .avatar {
  width: 35px;
  height: 35px;
}
.post .post-footer .comments-list .comment .comment-heading {
  display: block;
  width: 100%;
}
.post .post-footer .comments-list .comment .comment-heading .user {
  font-size: 14px;
  font-weight: bold;
  display: inline;
  margin-top: 0;
  margin-right: 10px;
}
.post .post-footer .comments-list .comment .comment-heading .time {
  font-size: 12px;
  color: #aaa;
  margin-top: 0;
  display: inline;
}
.post .post-footer .comments-list .comment .comment-body {
  margin-left: 50px;
}
.post .post-footer .comments-list .comment > .comments-list {
  margin-left: 50px;
}
.notf{
background-color: #dfedff;
color:black;
position:absolute;
width:300px;

right:0px;
text-align:center;
border-bottom:3px;
border-color:black;
}

</style>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
<script>
    //$(function () {

    //    $("#not").click(function () {
    //        $("#notification").slideDown('slow');

    //    })
    //    $("#close").click(function () {
    //        $("#notification").slideUp('slow');

    //    })
    //    $("#not").click(function () {
    //        $("p").show();
    //    });



    //});
    function myFunction() {
        var x = document.getElementById("notification");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }


  
    </script>

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Policy", "Commentaire")"> Policy</a>
            </div>
           
            <span class="topbar-badge animated rubberBand" style="color:red;">@Html.Encode(ViewData["nbreC"])</span>
            <span class="topbar-item-name"></span>
            <div style="padding-right:10px">
                <button class="btn btn-link" onclick="myFunction()" id="not">Notification</button>
                    

               
            </div>
        </div>
    </nav>
    <div id="notification" class="notf" style="display:none">
      
          @foreach (var item in Model.users)
        {


         <p>   @Html.DisplayFor(modelItem => item.firstName) was comment</p>
         
    

    }
        <button type="button" class="close" aria-label="Close" id="close">
            <span aria-hidden="true">&times;</span>
        </button>
     </div >
       
        <div class="title h5" style="margin-left:20px">
            <b> nbre de commentaires @Html.Encode(ViewData["nbre"])</b>

        </div>
        <br />
        <div class="title h5" style="margin-left:20px">
            @ViewBag.err
        </div>

        <div class="container" style="width:80%;margin-left:20px;">
            <div class="row" style="height:0px;">
                @foreach (var item in Model.commentaires)
                {
                    <div class="col-sm-8">
                        <div class="panel panel-white post panel-shadow">
                            <div class="post-heading">
                                <div class="pull-left image">
                                    <img src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar" alt="user profile image">
                                </div>
                                <div class="pull-left meta">
                                    <div class="title h5">
                                        <a href="#"><b>@Html.DisplayFor(modelItem => item.date)</b></a>

                                    </div>
                                   @if (item.user_id == 1)
                                   { <h6 class="text-muted time"> ahmed</h6>}
                                    @if (item.user_id == 2)
                                    { <h6 class="text-muted time"> sami</h6>}
                                   @if (item.user_id == 3)
                                   { <h6 class="text-muted time"> takwa</h6>}
                                </div>
                            </div>
                            <div class="post-description">
                                <p>@Html.DisplayFor(modelItem => item.text)</p>
                                <div class="stats">

                                    <a href="@Url.Action("Like", "Commentaire", new { id = item.id })" class="btn btn-default stat-item">
                                        <i class="fa fa-thumbs-up icon"></i>@Html.DisplayFor(modelItem => item.like)
                                    </a>
                                    <br />
                                    @if (item.user_id == 2)
                                    {

                                        <a href="@Url.Action("Edit", "Commentaire", new { id = item.id })" style="color:forestgreen" class="btn btn-default btn-sm">
                                            <i class="glyphicon glyphicon-edit"></i>
                                            <span>
                                                <strong>Edit</strong>
                                            </span>
                                        </a>



                                        <a href="@Url.Action("delete", "Commentaire", new { id = item.id })" style="color:forestgreen" class="btn btn-default btn-sm">
                                            <i class="glyphicon btn-default"></i>
                                            <span>
                                                <strong>delete</strong>
                                            </span>
                                        </a>




                                    }
                                    <br />

                                </div>
                            </div>
                        </div>
                    </div>
                }

             @if (@HttpContext.Current.Session["msg"].ToString() =="true")
             {
                <b style="background-color:red"> this msg contains a bad word sr </b>
             }
                  @using (Html.BeginForm("Create", "Commentaire"))
                {
                    <input type="text" id="txt" name="txt" class="form-control" rows="3" />
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" id="comment" class="btn-info" />
                    </div>
                }

            </div>
        </div>





</body>
</html>

CGA.NET-master/CGA-WEB/Views/Commentaire/Index2.cshtml
@model CGA_WEB.Models.CommentaireModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        .panel-shadow {
            box-shadow: rgba(0, 0, 0, 0.3) 7px 7px 7px;
        }

        .panel-white {
            border: 1px solid #dddddd;
        }

            .panel-white .panel-heading {
                color: #333;
                background-color: #fff;
                border-color: #ddd;
            }

            .panel-white .panel-footer {
                background-color: #fff;
                border-color: #ddd;
            }

        .post .post-heading {
            height: 95px;
            padding: 20px 15px;
        }

            .post .post-heading .avatar {
                width: 60px;
                height: 60px;
                display: block;
                margin-right: 15px;
            }

            .post .post-heading .meta .title {
                margin-bottom: 0;
            }

                .post .post-heading .meta .title a {
                    color: black;
                }

                    .post .post-heading .meta .title a:hover {
                        color: #aaaaaa;
                    }

            .post .post-heading .meta .time {
                margin-top: 8px;
                color: #999;
            }

        .post .post-image .image {
            width: 100%;
            height: auto;
        }

        .post .post-description {
            padding: 15px;
        }

            .post .post-description p {
                font-size: 14px;
            }

            .post .post-description .stats {
                margin-top: 20px;
            }

                .post .post-description .stats .stat-item {
                    display: inline-block;
                    margin-right: 15px;
                }

                    .post .post-description .stats .stat-item .icon {
                        margin-right: 8px;
                    }

        .post .post-footer {
            border-top: 1px solid #ddd;
            padding: 15px;
        }

            .post .post-footer .input-group-addon a {
                color: #454545;
            }

            .post .post-footer .comments-list {
                padding: 0;
                margin-top: 20px;
                list-style-type: none;
            }

                .post .post-footer .comments-list .comment {
                    display: block;
                    width: 100%;
                    margin: 20px 0;
                }

                    .post .post-footer .comments-list .comment .avatar {
                        width: 35px;
                        height: 35px;
                    }

                    .post .post-footer .comments-list .comment .comment-heading {
                        display: block;
                        width: 100%;
                    }

                        .post .post-footer .comments-list .comment .comment-heading .user {
                            font-size: 14px;
                            font-weight: bold;
                            display: inline;
                            margin-top: 0;
                            margin-right: 10px;
                        }

                        .post .post-footer .comments-list .comment .comment-heading .time {
                            font-size: 12px;
                            color: #aaa;
                            margin-top: 0;
                            display: inline;
                        }

                    .post .post-footer .comments-list .comment .comment-body {
                        margin-left: 50px;
                    }

                    .post .post-footer .comments-list .comment > .comments-list {
                        margin-left: 50px;
                    }

        .notf {
            background-color: #dfedff;
            color: black;
            position: absolute;
            width: 300px;
            right: 0px;
            text-align: center;
            border-bottom: 3px;
            border-color: black;
        }
    </style>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script>
    //$(function () {
    //    $("#close").click(function () {
    //        $("#notification").slideUp('slow');

    //    })
    //    $("#not").click(function () {
    //        $("#notification").slideDown('slow');

    //    })



    //});

        function myFunction() {
            var x = document.getElementById("notification");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }


    </script>

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Policy", "Commentaire")"> Policy</a>
            </div>

            <span class="topbar-badge animated rubberBand" style="color:red;">@Html.Encode(ViewData["nbreC"])</span>
            <span class="topbar-item-name"></span>
            <div style="padding-right:10px">
                <button class="btn btn-link" onclick="myFunction()" id="not">Notification</button>



            </div>
        </div>
    </nav>+
    <div id="notification" class="notf" style="display:none">

        @foreach (var item in Model.users)
        {


            <p>   @Html.DisplayFor(modelItem => item.firstName) was comment</p>



        }
        <button type="button" class="close" aria-label="Close" id="close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="title h5" style="margin-left:20px">
        <b> nbre de commentaires @Html.Encode(ViewData["nbre"])</b>

    </div>
    <br />
    <div class="title h5" style="margin-left:20px">
        @ViewBag.err
    </div>

    <div class="container" style="width:80%;margin-left:20px;">
        <div class="row" style="height:0px;">
            @foreach (var item in Model.commentaires)
            {
                <div class="col-sm-8">
                    <div class="panel panel-white post panel-shadow">
                        <div class="post-heading">
                            <div class="pull-left image">
                                <img src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar" alt="user profile image">
                            </div>
                            <div class="pull-left meta">
                                <div class="title h5">
                                    <a href="#"><b>@Html.DisplayFor(modelItem => item.date)</b></a>

                                </div>
                                @if (item.user_id == 1)
                                { <h6 class="text-muted time"> ahmed</h6>}
                                @if (item.user_id == 2)
                                { <h6 class="text-muted time"> sami</h6>}
                                @if (item.user_id == 3)
                                { <h6 class="text-muted time"> Emna</h6>}
                            </div>
                        </div>
                        <div class="post-description">
                            <p>@Html.DisplayFor(modelItem => item.text)</p>
                            <div class="stats">

                                <a href="@Url.Action("Like", "Commentaire", new { id = item.id })" class="btn btn-default stat-item">
                                    <i class="fa fa-thumbs-up icon"></i>@Html.DisplayFor(modelItem => item.like)
                                </a>
                                <br />
                                @if (item.user_id == 1)
                                {

                                    <a href="@Url.Action("Edit", "Commentaire", new { id = item.id })" style="color:forestgreen" class="btn btn-default btn-sm">
                                        <i class="glyphicon glyphicon-edit"></i>
                                        <span>
                                            <strong>Edit</strong>
                                        </span>
                                    </a>



                                        <a href="@Url.Action("delete", "Commentaire", new { id = item.id })" style="color:forestgreen" class="btn btn-default btn-sm">
                                            <i class="glyphicon btn-default"></i>
                                            <span>
                                                <strong>delete</strong>
                                            </span>
                                        </a>




                                }
                                <br />

                            </div>
                        </div>
                    </div>
                </div>
            }


            <b> @ViewBag.MyMessage</b>

            @using (Html.BeginForm("Create", "Commentaire"))
            {
                <input type="text" id="txt" name="txt" class="form-control" rows="3" />
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" id="comment" class="btn-info" />
                    </div>
            }

        </div>
    </div>





</body>
</html>

CGA.NET-master/CGA-WEB/Views/Commentaire/nbreCommentaire.cshtml
@model CGA_WEB.Models.CommentaireModels

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>nbreCommentaire</title>
</head>
<body>
    <div> 
   
     </div>
</body>
</html>